name: Docker Images
on:
  pull_request:
    types:
      - opened
  release:
    types:
      - published
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    name: "ufs_ftnutils container build test."
    steps:
      - name: Build and install the Docker dependencies.
        run: >
          sudo $(which apt-get) install git
          
          sudo $(which apt-get) remove docker docker-engine docker.io containerd runc
          
          sudo $(which apt-get) update
          
          sudo $(which apt-get) install ca-certificates curl gnupg lsb-release
          
          sudo $(which mkdir) -p /etc/apt/keyrings
          
          sudo $(which curl) -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          
          sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo $(which tee) /etc/apt/sources.list.d/docker.list > /dev/null
          
          sudo $(which chmod) a+r /etc/apt/keyrings/docker.gpg
          
          sudo $(which apt-get) update
          
          sudo $(which apt-get) install docker-ce docker-ce-cli containerd.io docker-compose-plugin
      - name: "Checkout `ufs_ftnutils.`"
        uses: actions/checkout@v2
        with:
          path: ufs_ftnutils
      - name: Build the Docker images.
        run: >
          cd ${GITHUB_WORKSPACE}/ufs_ftnutils/Docker
          
          $(which docker) build -f ${GITHUB_WORKSPACE}/ufs_ftnutils/Docker/ubuntu20.04.ufs_ftnutils.dockerfile --tag ubuntu20.04.ufs_ftnutils.containers:latest .
